<a href="https://colab.research.google.com/github/JJJuniorDev/ML-colab/blob/main/sgd_clf_knn_clf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn.datasets import fetch_openml
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier
mnist= fetch_openml('mnist_784', as_frame=False)

In [8]:
X, y= mnist.data, mnist.target

(70000,)

y shape: (70000,)
y unique: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
y_train_4 unique: (array([False]), array([56000]))


In [29]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
import numpy as np
from sklearn.metrics import confusion_matrix

print("y shape:", y.shape)
print("y unique:", np.unique(y))


sgd_clf= SGDClassifier(random_state=42)

y = y.astype(int)
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42, stratify=y
)
y_train_4 = (y_train == 4)
y_test_4 = (y_test == 4)

print(np.unique(y_train_4, return_counts=True))  # ora vedrai True e False

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_4)
y_train_pred=cross_val_predict(sgd_clf, X_train, y_train_4, cv=3)
cm=confusion_matrix(y_train_4, y_train_pred)
print(cm)

y shape: (70000,)
y unique: [0 1 2 3 4 5 6 7 8 9]
(array([False,  True]), array([50541,  5459]))
[[49515  1026]
 [  401  5058]]


In [32]:
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score
precision_score(y_train_4, y_train_pred)
recall_score(y_train_4, y_train_pred)
print(precision_score(y_train_4, y_train_pred))
print(recall_score(y_train_4, y_train_pred))
f1_score(y_train_4, y_train_pred)
print(f1_score(y_train_4, y_train_pred))

0.8313609467455622
0.9265433229529217
0.8763752923849952


In [39]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_predict
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

#print("y shape:", y.shape)
#print("y unique:", np.unique(y))

param_grid = {
    "n_neighbors": [3, 5, 7, 9],
    "weights": ["uniform", "distance"]
}

knn_clf= GridSearchCV(
    KNeighborsClassifier(),
    param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1
)

y = y.astype(int)
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.2, random_state=42, stratify=y
)
y_train_4 = (y_train == 4)
y_test_4 = (y_test == 4)

print(np.unique(y_train_4, return_counts=True))  # ora vedrai True e False

knn_clf.fit(X_train, y_train_4)
y_train_pred=cross_val_predict(knn_clf, X_train, y_train_4, cv=3)
cm=confusion_matrix(y_train_4, y_train_pred)
print(cm)
print(knn_clf.best_params_)

(array([False,  True]), array([50541,  5459]))
[[50439   102]
 [  201  5258]]
{'n_neighbors': 7, 'weights': 'uniform'}


In [40]:
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score
precision_score(y_train_4, y_train_pred)
recall_score(y_train_4, y_train_pred)
print(precision_score(y_train_4, y_train_pred))
print(recall_score(y_train_4, y_train_pred))
f1_score(y_train_4, y_train_pred)
print(f1_score(y_train_4, y_train_pred))

0.9809701492537314
0.9631800696098186
0.9719937147610684
